### ISSUE TITLE
Can model changes propagate outside of an imported template?

### ISSUE THREAD

**Issue by ivarbergman** [Juicy/imported-template#23]
Hi! Does `imported-template` handle data binding in "both ways"? Ie if I have something like this:

``` 
<input value="{{data.foo::change}}">
<template is="imported-template" model="{{data}}" content="test.html"></template>
```

where `test.html` contains

```
<input value="{{model.foo::change}}">
```

When I change the input value of the outer input-tag. The value `foo` is updated in the imported template as well. But if I change the foo value in the imported template the value change is not notified to the outer input tag.

Is this as expected? Can imported-template be used for these kind of bindings?

Thanks / Ivar

**Comment by warpech** [comment]
`imported-template` does nothing about the outer world. It does not propagate the model changes anywhere.

**But:**

In context of PuppetJs apps, the model changes are passed to other `imported-templates` because of dirty checking in `puppet-client`. If you are using that one (and not raw PuppetJs), you should get all the `imported-templates` notified.

cc @tomalec, @joozek78

**Comment by tomalec** [comment]
In demos we use [`<dom-bind-notifier>`](https://github.com/Juicy/dom-bind-notifier).
Starcounter apps uses [`<puppet-polymer-client>`](https://github.com/PuppetJs/puppet-polymer-client) to do the job.

Closing as answered. Feel free to reopen if you have any more questions
