### ISSUE TITLE
HTML Imports is deprecated and will be removed in M73

### ISSUE THREAD

**Issue by agarzon** [Juicy/imported-template#61]
What about ?

[Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.

**Comment by warpech** [comment]
Good question.

This component entirely builds around the HTML Imports spec. There is nothing we can do to change that in the long term, other than creating a new component that uses a different technology. 

I don't really consider ES modules a direct alternative, because ES modules are JS code, while we are interested in chunks of HTML. There is a new spec proposal: [HTML Modules](https://github.com/w3c/webcomponents/issues/645), which we have high hopes for.

For the time being, we make sure that `imported-template` works with the polyfill (https://github.com/webcomponents/webcomponentsjs, specifically: https://github.com/webcomponents/html-imports), so that it will continue to work in Chrome if you have that polyfill.

If you have any other suggestions, please share.
